import type { Metadata } from "next";
import { Work_Sans, Manjari } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";

const work_sans = Work_Sans({
  weight: ["200", "300", "400", "700", "800", "900"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-work-sans",
});
const manjari = Manjari({
  weight: ["100", "400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-manjari",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${work_sans.variable} ${manjari.variable}    antialiased`}
      >
        <ThemeProvider attribute={"class"} defaultTheme={"light"}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
